language: node_js
node_js:
  - "6"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --set gcc /usr/bin/gcc-5
cache:
  yarn: true
script: NODE_ENV=production yarn test
after_success:
  - pip install --user --upgrade requests
  - pip install --user azure-cli
  - export PATH=$PATH:~/.local/bin
  - PACKAGE_VERSION=$(node -p -e "require('./packages/network-navigator-powerbi/package.json').version")
  - FILE_NAME=network-navigator-$PACKAGE_VERSION.$TRAVIS_BUILD_NUMBER.pbiviz
  - if [ $TRAVIS_BRANCH = 'develop' ]; then az storage blob upload --container-name $AZURE_CONTAINER --file ./packages/network-navigator-powerbi/dist/powerbi/@essex/network-navigator-powerbi.pbiviz --name $FILE_NAME; fi